### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by Masynchin** [Smail000/SpaceInvader#1]
Hello!

I see that there is no README. Project's name looks interesting but I can't find any other information about repository. Can you describe your project? What is the status - is it your single repository or anyone can participate in project development? Is yes, can you provide guide for contributors?

**Comment by Smail000** [comment]
Hello! It seems i forgot to commit and push readme.md to github. If in short, it is 2D game, based on simple retro-games from past. I am doing this project for some reasons: firstly, i want to practice in js and learn pixi.js. Secondly, sometimes i dont have internet connection, like in journey, and i want to have fun with my two little brothers. So, i hope this game wont let us get bored and maybe interest my brothers in programming. Thx for your question 😁
